---
abstract: 'test scripts with run'
author:
  - 'sunnavy <sunnavy@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Script-Run
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  IPC::Run3: 0
  Test::Exception: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
