---
abstract: 'test the script with run'
author:
  - 'sunnavy <sunnavy@bestpractical.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Script-Run
no_index:
  directory:
    - inc
    - t
requires:
  IPC::Run3: 0
  Test::Exception: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
